sudo: required
language: node_js
node_js:
- '7'
services:
- docker
before_install:
- docker build -t dsumiskum/supermockapi .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push dsumiskum/supermockapi; fi
deploy:
  provider: npm
  email: dylan.sumiskum@live.com
  api_key: $NPM_TOKEN
  on:
    tags: true
